### ISSUE TITLE
All votes shown as rebellious when whip unknown?

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#139]
I think the whip guess in this case is "unknown" because "yes" and "not voting" is the same number. Should all the votes be shown in red, suggesting they're rebellions?

https://tvfy-ukraine.oaf.org.au/divisions/rada/2015-11-26/4803

![selection_001](https://cloud.githubusercontent.com/assets/48945/11531141/e52f12a0-994e-11e5-802d-a61a0cee3e18.png)

**Comment by equivalentideas** [comment]
Hmmm. I keep going back and forth on this. Every MP is voting differently to the majority of their fellow MPs, which is a rebellious vote by our measure. So I think this makes sense as is and we should leave it.

@henare What would you think if it was 17, 0, 2, 16? in that case the group of 17 are still voting against the majority of party MPs, which is how we describe rebellious votes: “<name> has voted against the majority of their party 1 time since February 2006”.

**Comment by henare** [comment]
@equivalentideas that's a very interesting question!

However I don't think it's one we're going to properly answer here. I think we leave this as-is and see what happens.
