### ISSUE TITLE
Policies calculation bug

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#144]
Here is one problem.
In this policy https://tvfy-ukraine.oaf.org.au/policies/5
the first MP in list of very strongly for (Михайло Добкін) ideologically can't vote for this division.
And when we open his page from this policy his voting is "No".
https://tvfy-ukraine.oaf.org.au/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE_%D0%94%D0%BE%D0%B1%D0%BA%D1%96%D0%BD/policies/5

So, is it a conflict of votings?

![dobkin1](https://cloud.githubusercontent.com/assets/14181306/11575272/c4b764f8-9a18-11e5-9589-c6272371e32f.PNG)
![dobkin2](https://cloud.githubusercontent.com/assets/14181306/11575273/c4db011a-9a18-11e5-9e2d-44ab0bcad889.PNG)

**Comment by henare** [comment]
The way this vote has been added to this policy says, "If you agree with 'За володіння українською мовою чиновниками' then you will vote "Ні" on [this vote](https://tvfy-ukraine.oaf.org.au/people/rada/%D0%97%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%BD%D0%BE%D0%BC%D1%83_%D0%B1%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0%D1%82%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%BA%D1%80%D1%83%D0%B3%D1%83/%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE_%D0%94%D0%BE%D0%B1%D0%BA%D1%96%D0%BD/divisions/2015-05-20/2144)".

Because Михайло Добкін voted no on that vote, he strongly agrees with the policy. Does this make sense @lisoffsky?

This can be confusing to work out! :)

**Comment by lisoffsky** [comment]
fixed but by somebody else. But that was a good lesson, thanks for explanation ans some practice:)
