### ISSUE TITLE
People pages with lots of rebellions are huge

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#146]
We show every rebellion on a person's page because in Australia there's not many. However Ukraine has people with 500+ rebellions so the page is really big.

It takes almost 15 seconds to [load this 1.5 MB page](https://tvfy-ukraine.oaf.org.au/people/rada/Загальнодержавному_багатомандатному_округу/Віталій_Чепинога) so I think we should fix this.

**Comment by equivalentideas** [comment]
- [x] If there's more than three show “Recent rebellions” instead of the full list:
  - [x] Change title of section
  - [x] Truncate list to 3
  - [x] Link to a filtered version of the divisions page that just shows rebellions
- [x] Add a page where people can see all of an MPs rebellions, probably a filtered version of 'recent votes'.
  - [x] only show rebellions
  - [x] change title
  - [x] change intro paragraph
  - [x] change text for 'no recorded divisions during membership'
  - [x] change meta title and description

**Comment by henare** [comment]
Great stuff :star2:
