### ISSUE TITLE
MP page does not sort correctly in Ukrainian

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#148]
Edit by @henare: This is incorporates #147. Sorting on name or constituency on the MP page doesn't sort in the correct order for the Ukrainian language.

---

So we need help not only with sorting by oblast (#143) but also by name

When I try to sort by name on MPs page https://rada4you.org/people, what is default sorting, I see that sorting starts not by Ukrainian alphabet. Now page starts from letter "Є", but it should start from "А".

Can I somehow help with alphabet and oblasts, if needed?

**Comment by henare** [comment]
@lisoffsky I think I've fixed this, can you please check?

**Comment by lisoffsky** [comment]
I'm afraid not fully working.
In the bottom after MP Андрій Шипко sorting looks broken. Next after him MP Вікторія Сюмар should be way higher in a list. As other MPs.
Looks like sorting now works by their English names (and the same for oblasts) where Ukrainian letter "Ш" spelled like "sh" in English, e.g. That's why Ukrainian "T" surnames go after "Ш". 

That's my guess.

**Comment by beastie87** [comment]
m.constituency  is English or Ukrainian ? 
if m.constituency is Ukrainian 
not use transliterate

**Comment by henare** [comment]
> Looks like sorting now works by their English names (and the same for oblasts) where Ukrainian letter "Ш" spelled like "sh" in English, e.g. That's why Ukrainian "T" surnames go after "Ш".
> 
> That's my guess.

Yes, you're right! https://github.com/OPORA/publicwhip/commit/cceba4b71d9b2f5a3613e3a164b5ce3bc4065191

Reopening this issue to investigate if we can sort in Ukrainian.

**Comment by henare** [comment]
We know that [sorting in transliterated Ukrainian](https://github.com/OPORA/publicwhip/commit/cceba4b71d9b2f5a3613e3a164b5ce3bc4065191) doesn't [sort correctly in the Ukrainian alphabet](https://github.com/OPORA/publicwhip/issues/148#issuecomment-162599620).

I next looked around for ways to get Ruby to sort correctly in Ukrainian. The [TwitterCLDR library](https://github.com/twitter/twitter-cldr-rb#sorting-collation) can do that but it doesn't do `#sort_by`. Writing something to do this ourselves seems like complex yak shaving.

So that made me look at doing this sorting in the DB again because I know databases should be able to sort this correctly. The reason why we're doing sorting in Ruby is because we've got a pretty complex sort hierarchy and all the attributes we sort on aren't accessible in the DB in a simple way (i.e. rebellions & attendance for the _Person_).

I think the most sensible thing to do is to sort in the DB for the queries we can and leave the ones we can't as-is. This will mean that there's not great secondary sorting on rebellions and attendance in Ukrainian because it will use the dumb name sorting for those two only.

It also means we lose our 4th level tertiary sorting `-m.entered_house.to_time.to_i` on the queries we start using the DB for. It seems like there's such a remote chance of this ever being actually used in sorting that it's fine we lose this.

**Comment by henare** [comment]
@lisoffsky I've made this change so sorting by name and oblast should be working, can you please check again?

I've also opened #159 to track the remaining smaller issue that we're not planning to resolve for this part of the project.

**Comment by lisoffsky** [comment]
Yes, it now sorts very well! Thank you, Henare!

**Comment by beastie87** [comment]
Maybe use need  gem 'chars' for sort_by
require 'chars'
a= ['Борис','Андрей','Яна', 'Мария']
p a.sort_by {|word| word.chars}
#results => ["Андрей", "Борис", "Мария", "Яна"]

**Comment by lisoffsky** [comment]
@beastie87 beware, your example is in Russian language

**Comment by beastie87** [comment]
Sorry Ukrainian is also  Cyrillic
require 'chars'
a= ['Андрій','Марія', 'Василь', 'Геннадій']
p a.sort_by {|word| word.chars}
#results=>["Андрій", "Василь", "Геннадій", "Марія"]
But Ukrainian letters "і" and 'є' is the problem
require 'chars'
a= ['Андрій','Марія', 'Василь', 'Геннадій','Іван', 'Євген']
p a.sort_by {|word| word.chars}
#results=>["Євген", "Іван", "Андрій", "Василь", "Геннадій", "Марія"]

**Comment by henare** [comment]
> Yes, it now sorts very well! Thank you, Henare!

@lisoffsky woohoo!

> Maybe use need gem 'chars' for sort_by

@beastie87 that's really interesting. I wonder if we could expand chars to support Ukrainian?
