### ISSUE TITLE
API people.json

### ISSUE THREAD

**Issue by beastie87** [OPORA/publicwhip#153]
I am read https://rada4you.org/help/data  and and I have questions 
1. request GET https://rada4you.org/api/v1/people.json?key=[api_key]
gives us:
id: 18028,  # It is id depty for rada: http://rada.gov.ua?
latest_member: 
{
id: 534, # it is local databases id? 
name: 
{
first: "Павло",
last: "Костенко"
},
electorate: "обраний в Раду за списком партії",
house: "rada",
party: "Фракція Політичної партії "Об'єднання "САМОПОМІЧ""
}
},
need to call these different keys, so as to be clear what this data
Example:
id_deputy_rada: 18028, 
latest_member: 
{
id: 534, # it is local databases id? 
name: 
{
first: "Павло",
last: "Костенко"
},
electorate: "обраний в Раду за списком партії",
house: "rada",
party: "Фракція Політичної партії "Об'єднання "САМОПОМІЧ""
}
},

**Comment by henare** [comment]
> id: 18028, # It is id depty for rada: http://rada.gov.ua?

This is the Person ID. Yes, we are using the Rada ID for this.

> id: 534, # it is local databases id? 

This is the Member ID. Yes, it is an internally generated ID.

The internal data structures of the application are not the best, are confusing, and do not map to any standards, such as [Popolo](http://www.popoloproject.com/). Rather than make changes to this API we should just make it Popolo compatible: https://github.com/openaustralia/publicwhip/issues/919

I'll close this in favour of making the API Popolo compatible.
