### ISSUE TITLE
Commit code @beastie

### ISSUE THREAD

**Issue by beastie87** [OPORA/publicwhip#164]
Hi!
Where I can commit  my code?
Thank you!

**Comment by henare** [comment]
Hi @beastie87, great to see your first commit!

With simple ones like that you can commit straight to `develop`, however don't forget to make sure your tests pass as [we run Travis CI](https://travis-ci.org/OPORA/publicwhip).

For anything more complex you can also open a pull request and ask us to review and merge it.

**Comment by henare** [comment]
I should also add a bit about translations. Obviously we're trying to change as little as possible how the application works so that we can merge this upstream at some time soon in the future.

For any translations to views we're just copying the view to a localised template, committing that, then making any changes. This allows us to really easily diff these views against the originals to see the changes.

For any changes to helpers we're trying to use gettext where possible ([example](https://github.com/OPORA/publicwhip/commit/c37eee09e04c3ab0b985cd368b9c83cf788efdd3)).

Using these techniques allows the application's tests to still pass with no changes because they're still testing against the English version.

If there's no easy way to translate helpers using gettext we're falling back to these hacky exceptions of checking the locale in an if block, ([example](https://github.com/OPORA/publicwhip/commit/34ddab08b399ae3f5020c48457ab44d60c6a8e83)). This should be used as a last resort only because we'll have to change this when we merge upstream.

**Comment by henare** [comment]
@beastie87 please open a pull request with your changes: https://github.com/OPORA/publicwhip/compare/develop...OPORA:beastie

While there's lots of good changes, there are some hacks in there I'd be strongly against merging.
