### ISSUE TITLE
Проблема з дворазовим відображенням депутата в списку

### ISSUE THREAD

**Issue by dmytrohoi** [OPORA/publicwhip#239]
У списку депутатів, за сортуванням "Відвідуваність" депутат відображається як від партії, та як позафракційний.

Сама проблема - 
![image](https://cloud.githubusercontent.com/assets/6693657/18731784/e4cd1a96-8066-11e6-8dc5-42e4dfd59a15.png)

**Comment by beastie87** [comment]
@demiantorr дякуємо за повідомлення про проблему. Дана ситуація виникла так як на сайті ВР http://itd.rada.gov.ua/mps/info/page/19126 вказана дата НАБУТТЯ ДЕПУТАТСЬКИХ ПОВНОВАЖЕНЬ: 5 червня 2015р., але в фракційних переходах він був депутатом з 27.10.2014 http://w1.c1.rada.gov.ua/pls/site2/p_deputat_fr_changes?d_id=19126, тому  виходить розбіжність і  депутат повторювався двічі.

**Comment by beastie87** [comment]
This issue arose in connection with the issue at Council, namely the difference deputatstva dates of entry http://itd.rada.gov.ua/mps/info/page/19126  and stay in fractions http://w1.c1.rada.gov.ua/pls/site2/p_deputat_fr_changes?d_id=19126, so I added a request group (: gid) in order to are repetition, this change will consume when corrected date on http://w1.c1.rada.gov.ua/pls/site2/p_deputat_fr_changes?d_id=19126 or  http://itd.rada.gov.ua/mps/info/page/19126
