### ISSUE TITLE
Ukrainian translation for 'Before being' in faction changes paragraph

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#36]
Extracted from #33:

> is it here where we add information about faction switches?

How does this help users? Where would they expect this information to be?

**Comment by henare** [comment]
Isn't it already [shown here](https://tvfy-ukraine.oaf.org.au/people/rada/Загальнодержавному_багатомандатному_округу/Давид_Макар'ян)?

![selection_001](https://cloud.githubusercontent.com/assets/48945/11136001/b8fb028e-89fe-11e5-88a7-a683197f5a47.png)

**Comment by equivalentideas** [comment]
Is this the equivalent of membership changes in They Vote For You like: https://theyvoteforyou.org.au/people/representatives/new_england/barnaby_joyce or something else?

**Comment by henare** [comment]
Yes, that's exactly how it works.

**Comment by equivalentideas** [comment]
> Yes, that's exactly how it works.

:+1: Great.

I'm going to make this issue about needing the Ukrainian translation for 'Before being' for:

> Before being Група "Партія "Відродження" Верхо́вна Ра́да Украї́ни for Виборчому округу №147, Олег Кулініч was Група "Відродження" Верхо́вна Ра́да Украї́ни for Виборчому округу №147 і Група "Економічний розвиток" Верхо́вна Ра́да Украї́ни for Виборчому округу №147.

This relates to #59 as well.

Help needed on this one @orybiy @mmitre @lisoffsky :smile:

**Comment by lisoffsky** [comment]
Can we make it this way?

Before being = До членства у
but then the changing of endings should happen and "Фракція Партії..." would better sound as "Фракці[ ї ] Партії..".
If this can be done, then for groups changes could look like this "Група..." as "Груп[ і ]...
And if this changes are possible please add this to all the factions and groups which listed on a page

Also I think in the text
[Before being Група "Партія "Відродження" Верхо́вна Ра́да Украї́ни for Виборчому округу №147, Олег Кулініч was Група "Відродження" Верхо́вна Ра́да Украї́ни for Виборчому округу №147 і Група "Економічний розвиток" Верхо́вна Ра́да Украї́ни for Виборчому округу №147.]
words "Верхо́вна Ра́да Украї́ни" can be erased because they don't give any additional sense since we have 1 House Parliament. 

the word "was" in the text can be translated differently for male and female
female was = була у
male was = був у

what do you think?

**Comment by orybiy** [comment]
I suggest to add this information under the title Faction switches 
 Faction switches  - Міжфракційні переходи
There are a lot of odd and unnecessary words. It can be simple:
Faction switches: non-member of factions (please add time period if it is possible)
Міжфракційні переходи: позафракційний/на [time period]

@lisoffsky

**Comment by henare** [comment]
> There are a lot of odd and unnecessary words. It can be simple

I agree with @orybiy. In Australia the sentence makes sense because it's rare for MPs to change parties and a sentence is nicer for people to read.

In Ukraine it's more common to change faction, and that history is important, so a simple list is probably quicker and easier to understand.

I've gone ahead and done this. Here's what it looks like:

![selection_001](https://cloud.githubusercontent.com/assets/48945/11354258/549cf998-929e-11e5-8005-40d53be66128.png)

![selection_002](https://cloud.githubusercontent.com/assets/48945/11354262/5969d0c2-929e-11e5-965e-1b6f0fe22e66.png)

If there's any changes you want, please open a new issue.
