### ISSUE TITLE
Divisions page is ridiculously slow

### ISSUE THREAD

**Issue by henare** [OPORA/publicwhip#92]
Because there are so many divisions the page is taking me 23s to load and is 4MB(!).

**Comment by equivalentideas** [comment]
Is it the query that is slow or the time to download and render the HTML?

**Comment by henare** [comment]
Can't you see the problem?

**Comment by equivalentideas** [comment]
Yeah, I've got 4mb of HTML from the live site and in the mini profiler I can see it takes around 3ms to render each division on my machine. There's 3000 divisions on the live /divisions page, so that's 9seconds just to render the divisions.

So one solution could be to reduce the number of divisions on that page. Is there a shorter time period that makes sense with the information? Month?

@henare I think we should address this todo cause there may be interface changes I could help with before I leave.

**Comment by henare** [comment]
@equivalentideas yes, that would be awesome!

**Comment by equivalentideas** [comment]
After discussion with @henare , we think a good solution for the [MVP](https://github.com/OPORA/publicwhip/milestones/MVP) will be to replace the pagination by year with pagination by a number of votes.

I think a good number would be:
- few enough to speed up the page load to under a second if possible
- enough that you can see at least one day of votes
- not so many that you need to scroll for ever to get to the pagination

**Comment by equivalentideas** [comment]
Ok I've done this in https://github.com/OPORA/publicwhip/compare/b553ba7...9cad1c37e755

Doesn't quite load in under a second ;-) but it's _loads_ faster.

**Comment by henare** [comment]
_So much_ better - nice work @equivalentideas.
