### ISSUE TITLE
Translate individual vote page description shown in search/social media

### ISSUE THREAD

**Issue by equivalentideas** [OPORA/publicwhip#93]
@orybiy @mmitre @lisoffsky could you please translate:

> "A vote in the Rada on 14.07.2015."

from

> A vote in the Rada on 14.07.2015. Поіменне голосування про поправку №82 народних депутатів Крулька І.І., Тарасюка Б.І. до проекту Закону про внесення змін до деяких законодавчих актів України щодо ...

Thanks :smile_cat:

**Comment by lisoffsky** [comment]
I think this works
A vote in the Rada on - Голосування у Раді

**Comment by henare** [comment]
I think this issue is actually talking about the [division show meta description tag](https://github.com/OPORA/publicwhip/blob/develop/app/views/divisions/show.uk.html.haml#L1).

@lisoffsky so we actually need this phrase translated:

> A vote in the #{house_name} on #{date}. #{division name}

As `house_name` is "Rada" we also need this bit translated in this context.

I hope that makes sense :smiley:

**Comment by lisoffsky** [comment]
okay, thanks for clarification!
Hope this will help. We have one-house Parliament, so I think we can even erase word Rada and have this kind of wording "Голосування від 14.07.2015. Поіменне голосування про поправку №82 народних депутатів Крулька І.І., Тарасюка Б.І. до проекту Закону..."
does this make sense?

**Comment by henare** [comment]
@lisoffsky Great! Here's a real example after I made that change:

> Голосування від 17.06.2015. Поіменне голосування про повернення до розгляду проекту Постанови про Заяву Верховної Ради України щодо збереження в Україні самобутності та культурної спадщини кримськи...
